import mongoose from "mongoose";
import { Async, AppError } from "../lib";
import { Agent } from "../models";

export const getAllAgents = Async(async (req, res, next) => {
  const agents = await Agent.find().select(
    "avatar username email phone location listing"
  );

  res.status(200).json(agents);
});

export const getAgent = Async(async (req, res, next) => {
  const { agentId } = req.params;

  const agent = await Agent.findById(agentId);

  if (!agent) return next(new AppError(404, "Agent does not exists"));

  res.status(200).json(agent);
});

const AGENTS = [
  {
    username: "Paolo Nutini",
    email: "nutin@io.com",
    birthDate: "02-28-1996",
    avatar:
      "https://images.unsplash.com/photo-1633332755192-727a05c4013d?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dXNlcnxlbnwwfHwwfHx8MA%3D%3D",
    listing: [],
    location: {
      name: "Eilat",
      displayName: "Eilat, South District, Israel",
      city: "Eilat",
      country: "Israel",
      state: "South District",
      addressType: "city",
      postcode: "88000",
      lat: "29.5569348",
      lon: "34.9497949",
    },
    bio: "Passionate about real estate and helping clients find their dream homes. With a decade of experience, I'm here to make your real estate dreams a reality. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#18457 865 8745",
    taxNumber: "TX 87D0 678H PQ45",
    phone: "+021 541 236 4580",
    agency: {
      title: "All American Real Estate",
      agencyLicense: "3124 9764 9700 234",
    },
    serviceArea: {
      name: "Tel Aviv",
      displayName: "Tel Aviv, Central District, Israel",
      city: "Tel Aviv",
      country: "Israel",
      state: "Central District",
      addressType: "city",
      postcode: "62120",
      lat: "32.0852999",
      lon: "34.7817676",
    },
  },
  {
    username: "Alice Johnson",
    email: "alice@io.com",
    birthDate: "03-15-1988",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dXNlcnxlbnwwfHwwfHx8MA%3D%3D",
    listing: [],
    location: {
      name: "New York City",
      displayName: "New York City, New York, USA",
      city: "New York City",
      country: "USA",
      state: "New York",
      addressType: "city",
      postcode: "10001",
      lat: "40.712776",
      lon: "-74.005974",
    },
    bio: "Experienced real estate agent dedicated to finding the perfect property for you. I love helping clients make their real estate dreams come true. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#29386 765 2398",
    taxNumber: "TX 65Z0 876A KL12",
    phone: "+021 555 987 6543",
    agency: {
      title: "Big Apple Realty",
      agencyLicense: "9876 5432 1234 765",
    },
    serviceArea: {
      name: "Manhattan",
      displayName: "Manhattan, New York, USA",
      city: "New York City",
      country: "USA",
      state: "New York",
      addressType: "city",
      postcode: "10120",
      lat: "40.712776",
      lon: "-74.005974",
    },
  },
  {
    username: "Ella Davis",
    email: "ella@io.com",
    birthDate: "09-20-1992",
    avatar:
      "https://plus.unsplash.com/premium_photo-1688350808212-4e6908a03925?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fHVzZXJ8ZW58MHx8MHx8fDA%3D",
    listing: [],
    location: {
      name: "London",
      displayName: "London, Greater London, United Kingdom",
      city: "London",
      country: "United Kingdom",
      state: "Greater London",
      addressType: "city",
      postcode: "SW1A 1AA",
      lat: "51.5073509",
      lon: "-0.1277583",
    },
    bio: "Specializing in the London real estate market. I'm dedicated to helping you find the perfect property in this vibrant city. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#12345 678 9012",
    taxNumber: "TX 12C3 456B KR98",
    phone: "+044 20 1234 5678",
    agency: {
      title: "London Properties",
      agencyLicense: "8765 4321 1234 567",
    },
    serviceArea: {
      name: "Birmingham",
      displayName: "Birmingham, West Midlands, United Kingdom",
      city: "Birmingham",
      country: "United Kingdom",
      state: "West Midlands",
      addressType: "city",
      postcode: "B1 1AA",
      lat: "52.486243",
      lon: "-1.890401",
    },
  },
  {
    username: "David Miller",
    email: "david@io.com",
    birthDate: "12-05-1980",
    avatar:
      "https://images.unsplash.com/photo-1557862921-37829c790f19?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fHVzZXJ8ZW58MHx8MHx8fDA%3D",
    listing: [],
    location: {
      name: "Los Angeles",
      displayName: "Los Angeles, California, USA",
      city: "Los Angeles",
      country: "USA",
      state: "California",
      addressType: "city",
      postcode: "90001",
      lat: "34.052235",
      lon: "-118.243683",
    },
    bio: "Bringing extensive knowledge of the Los Angeles real estate market, I'm here to assist you in finding your dream home. With a strong background in negotiations, I will guide you through the process. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#76543 210 7890",
    taxNumber: "TX 21C7 654F PQ32",
    phone: "+1 213 555 1234",
    agency: {
      title: "LA Realty Group",
      agencyLicense: "4321 9876 5678 123",
    },
    serviceArea: {
      name: "San Francisco",
      displayName: "San Francisco, California, USA",
      city: "San Francisco",
      country: "USA",
      state: "California",
      addressType: "city",
      postcode: "94101",
      lat: "37.7749295",
      lon: "-122.4194155",
    },
  },
  {
    username: "Sophia Wilson",
    email: "sophia@io.com",
    birthDate: "06-30-1987",
    avatar:
      "https://images.unsplash.com/photo-1534180477871-5d6cc81f3920?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fHVzZXJ8ZW58MHx8MHx8fDA%3D",
    listing: [],
    location: {
      name: "Sydney",
      displayName: "Sydney, New South Wales, Australia",
      city: "Sydney",
      country: "Australia",
      state: "New South Wales",
      addressType: "city",
      postcode: "2000",
      lat: "-33.8688197",
      lon: "151.2092955",
    },
    bio: "Helping clients find their dream homes in the beautiful city of Sydney. Experienced in waterfront properties and luxury estates. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#78965 432 5678",
    taxNumber: "TX 89J1 345K QR76",
    phone: "+61 2 5555 6789",
    agency: {
      title: "Sydney Realty Solutions",
      agencyLicense: "5678 1234 5678 123",
    },
    serviceArea: {
      name: "Melbourne",
      displayName: "Melbourne, Victoria, Australia",
      city: "Melbourne",
      country: "Australia",
      state: "Victoria",
      addressType: "city",
      postcode: "3000",
      lat: "-37.8136276",
      lon: "144.9630576",
    },
  },
  {
    username: "Michael Smith",
    email: "michael@io.com",
    birthDate: "08-10-1994",
    avatar:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dXNlcnxlbnwwfHwwfHx8MA%3D%3D",
    listing: [],
    location: {
      name: "Miami",
      displayName: "Miami, Florida, USA",
      city: "Miami",
      country: "USA",
      state: "Florida",
      addressType: "city",
      postcode: "33101",
      lat: "25.7616798",
      lon: "-80.1917902",
    },
    bio: "Expert in Miami's real estate market. I specialize in beachfront properties and luxury condos. Let me help you find your dream home in the sunny city of Miami. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#12345 678 9012",
    taxNumber: "TX 12C3 456B KR98",
    phone: "+1 305 555 1234",
    agency: {
      title: "Miami Luxury Realty",
      agencyLicense: "8765 4321 1234 567",
    },
    serviceArea: {
      name: "Fort Lauderdale",
      displayName: "Fort Lauderdale, Florida, USA",
      city: "Fort Lauderdale",
      country: "USA",
      state: "Florida",
      addressType: "city",
      postcode: "33301",
      lat: "26.1224386",
      lon: "-80.1373174",
    },
  },
  {
    username: "Olivia Brown",
    email: "olivia@io.com",
    birthDate: "05-12-1985",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661768742069-4de270a8d9fa?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjIxfHx1c2VyfGVufDB8fDB8fHww",
    listing: [],
    location: {
      name: "Paris",
      displayName: "Paris, Île-de-France, France",
      city: "Paris",
      country: "France",
      state: "Île-de-France",
      addressType: "city",
      postcode: "75001",
      lat: "48.856613",
      lon: "2.352222",
    },
    bio: "Specializing in Parisian real estate, I'm here to assist you in finding the perfect property in the heart of the city of lights. Whether you're looking for a charming apartment or a historic mansion, I've got you covered. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#45678 901 2345",
    taxNumber: "TX 45R6 789B PL20",
    phone: "+33 1 5555 6789",
    agency: {
      title: "Paris Prestige Properties",
      agencyLicense: "3456 7890 1234 567",
    },
    serviceArea: {
      name: "Versailles",
      displayName: "Versailles, Île-de-France, France",
      city: "Versailles",
      country: "France",
      state: "Île-de-France",
      addressType: "city",
      postcode: "78000",
      lat: "48.801408",
      lon: "2.130122",
    },
  },
  {
    username: "James Lee",
    email: "james@io.com",
    birthDate: "11-08-1982",
    avatar:
      "https://images.unsplash.com/photo-1562788869-4ed32648eb72?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjAwfHx1c2VyfGVufDB8fDB8fHww",
    listing: [],
    location: {
      name: "San Francisco",
      displayName: "San Francisco, California, USA",
      city: "San Francisco",
      country: "USA",
      state: "California",
      addressType: "city",
      postcode: "94102",
      lat: "37.7749295",
      lon: "-122.4194155",
    },
    bio: "Dedicated to the San Francisco real estate market, I'm here to help you find your dream home in the Bay Area. With expertise in both residential and commercial properties, I'm your go-to agent. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#56789 012 3456",
    taxNumber: "TX 56F7 890P L345",
    phone: "+1 415 555 1234",
    agency: {
      title: "Bay Area Realty",
      agencyLicense: "2345 6789 0123 456",
    },
    serviceArea: {
      name: "Palo Alto",
      displayName: "Palo Alto, California, USA",
      city: "Palo Alto",
      country: "USA",
      state: "California",
      addressType: "city",
      postcode: "94301",
      lat: "37.4418834",
      lon: "-122.1430195",
    },
  },
  {
    username: "Emma White",
    email: "emma@io.com",
    birthDate: "07-21-1989",
    avatar:
      "https://images.unsplash.com/photo-1520333789090-1afc82db536a?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHVzZXJ8ZW58MHwwfDB8fHww",
    listing: [],
    location: {
      name: "Toronto",
      displayName: "Toronto, Ontario, Canada",
      city: "Toronto",
      country: "Canada",
      state: "Ontario",
      addressType: "city",
      postcode: "M5H 1W2",
      lat: "43.653225",
      lon: "-79.383186",
    },
    bio: "With a deep understanding of the Toronto real estate market, I'm here to assist you in finding the perfect property in this vibrant city. Whether you're a first-time buyer or an experienced investor, I'm ready to help. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#98765 432 1098",
    taxNumber: "TX 98J7 654M KQ12",
    phone: "+1 416 555 1234",
    agency: {
      title: "Toronto Realty Group",
      agencyLicense: "6789 0123 4567 890",
    },
    serviceArea: {
      name: "Mississauga",
      displayName: "Mississauga, Ontario, Canada",
      city: "Mississauga",
      country: "Canada",
      state: "Ontario",
      addressType: "city",
      postcode: "L5B 2C9",
      lat: "43.5890452",
      lon: "-79.6441198",
    },
  },
  {
    username: "Liam Brown",
    email: "liam@io.com",
    birthDate: "04-17-1983",
    avatar:
      "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHVzZXJ8ZW58MHwwfDB8fHww",
    listing: [],
    location: {
      name: "Melbourne",
      displayName: "Melbourne, Victoria, Australia",
      city: "Melbourne",
      country: "Australia",
      state: "Victoria",
      addressType: "city",
      postcode: "3001",
      lat: "-37.8136276",
      lon: "144.9630576",
    },
    bio: "Experienced in the Melbourne real estate market, I'm here to help you find your dream property in this vibrant city. I specialize in a wide range of properties, from apartments to luxury estates. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#34567 890 1234",
    taxNumber: "TX 34H7 890E OP56",
    phone: "+61 3 5555 6789",
    agency: {
      title: "Melbourne Real Estate",
      agencyLicense: "4567 8901 2345 678",
    },
    serviceArea: {
      name: "Geelong",
      displayName: "Geelong, Victoria, Australia",
      city: "Geelong",
      country: "Australia",
      state: "Victoria",
      addressType: "city",
      postcode: "3220",
      lat: "-38.149918",
      lon: "144.361719",
    },
  },
  {
    username: "Ava Miller",
    email: "ava@io.com",
    birthDate: "10-11-1985",
    avatar:
      "https://plus.unsplash.com/premium_photo-1661330050093-e3160c482b05?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQxfHx1c2VyfGVufDB8MHwwfHx8MA%3D%3D",
    listing: [],
    location: {
      name: "Berlin",
      displayName: "Berlin, Berlin, Germany",
      city: "Berlin",
      country: "Germany",
      state: "Berlin",
      addressType: "city",
      postcode: "10115",
      lat: "52.520008",
      lon: "13.4049540",
    },
    bio: "As a dedicated real estate agent in Berlin, I'm here to assist you in finding your ideal property in the vibrant capital of Germany. Whether you're looking for a cozy apartment or a spacious villa, I'm here to help. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#23456 789 0123",
    taxNumber: "TX 23K4 567B OL67",
    phone: "+49 30 5555 6789",
    agency: {
      title: "Berlin Property Solutions",
      agencyLicense: "5678 9012 3456 789",
    },
    serviceArea: {
      name: "Potsdam",
      displayName: "Potsdam, Brandenburg, Germany",
      city: "Potsdam",
      country: "Germany",
      state: "Brandenburg",
      addressType: "city",
      postcode: "14467",
      lat: "52.398852",
      lon: "13.065822",
    },
  },
  {
    username: "Oliver Wilson",
    email: "oliver@io.com",
    birthDate: "11-28-1980",
    avatar:
      "https://images.unsplash.com/photo-1612947707010-0fe0c69e780b?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjUwfHx1c2VyfGVufDB8MHwwfHx8MA%3D%3D",
    listing: [],
    location: {
      name: "Madrid",
      displayName: "Madrid, Madrid, Spain",
      city: "Madrid",
      country: "Spain",
      state: "Madrid",
      addressType: "city",
      postcode: "28001",
      lat: "40.4167754",
      lon: "-3.7037902",
    },
    bio: "With a passion for real estate in Madrid, I'm here to help you find your dream property in the vibrant Spanish capital. Whether it's a historic apartment or a modern condo, I've got you covered. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    agentId: "#98765 432 1098",
    taxNumber: "TX 98J7 654M KQ12",
    phone: "+34 91 555 6789",
    agency: {
      title: "Madrid Real Estate",
      agencyLicense: "6789 0123 4567 890",
    },
    serviceArea: {
      name: "Toledo",
      displayName: "Toledo, Castilla-La Mancha, Spain",
      city: "Toledo",
      country: "Spain",
      state: "Castilla-La Mancha",
      addressType: "city",
      postcode: "45001",
      lat: "39.862832",
      lon: "-4.027323",
    },
  },
];
